name: Render documentation

# see https://github.com/actions/setup-python#using-setup-python-with-a-self-hosted-runner
# for artifact handling and SBOM: https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

on:
  push:
  #pull_request: # Not necessary, as it is already been executed on push
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

jobs:
  doc_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13.7"
        # use uv now:
        #cache: 'pip' # caching pip dependencies

    - name: print versions for debugging
      run: |
        python --version ; pip --version ; whoami ; pwd

    - name: Install System Dependencies
      run: sudo apt-get update && sudo apt-get install -y graphviz plantuml

    - name: Install uv
      run: pip install uv

    - name: Install Python dependencies
      run: |
        ls -al
        uv venv
        uv sync --project ./components/comp_1/sphinx-needs
        ls -al

    - name: Lint sphinx files
      run: |
        ls -al
        uv run sphinx-lint
        ls -al

    - name: Render Sphinx Documentation
      run: >
        uv run sphinx-build
        -b html
        ./components/comp_1/sphinx-needs ./public/comp_1
        --jobs=auto
        --show-traceback
        --keep-going
        --fail-on-warning

    - name: Archive sphinx public folder
      uses: actions/upload-artifact@v4
      with:
        name: sphinx-public
        path: |
          ./public/
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}


  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: doc_build
    if: github.ref_name == github.event.repository.default_branch
    steps:
      - name: Download sphinx public folder
        uses: actions/download-artifact@v4
        with:
          name: sphinx-public
          path: ./public/
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
